# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\大三上\计算机通信网络\大作业\新建文件夹\src\exp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exp(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 531)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 180, 200, 200))
        self.label.setStyleSheet("border-radius:10px;\n"
"background-color: white;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(220, 200, 40, 40))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 200, 40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 200, 40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 200, 40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(340, 240, 40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 240, 40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 240, 40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(300, 240, 40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(340, 280, 40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 280, 40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(260, 280, 40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(300, 280, 40, 40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(340, 320, 40, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(220, 320, 40, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(260, 320, 40, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(300, 320, 40, 40))
        self.pushButton_15.setObjectName("pushButton_15")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_1.setText(_translate("Form", "😙"))
        self.pushButton_2.setText(_translate("Form", "🤯"))
        self.pushButton_3.setText(_translate("Form", "😅"))
        self.pushButton_4.setText(_translate("Form", "😮"))
        self.pushButton_8.setText(_translate("Form", "😡"))
        self.pushButton_5.setText(_translate("Form", "😒"))
        self.pushButton_6.setText(_translate("Form", "😚"))
        self.pushButton_7.setText(_translate("Form", "😉"))
        self.pushButton_12.setText(_translate("Form", "🙇‍"))
        self.pushButton_9.setText(_translate("Form", "😳"))
        self.pushButton_10.setText(_translate("Form", "😰"))
        self.pushButton_11.setText(_translate("Form", "🙁"))
        self.pushButton_16.setText(_translate("Form", "😓"))
        self.pushButton_13.setText(_translate("Form", "😏"))
        self.pushButton_14.setText(_translate("Form", "😟"))
        self.pushButton_15.setText(_translate("Form", "😀"))
