# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\大三上\计算机通信网络\大作业\新建文件夹\src\Forget_Password.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QCursor, QColor

class Ui_Forget_Password(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(662, 677)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 设置窗口背景透明
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(140, 20, 350, 425))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 350, 425))
        self.label.setStyleSheet("background-color: rgba(30,30,40,240);\n"
"border-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Email_Text = QtWidgets.QLineEdit(self.widget)
        self.Email_Text.setGeometry(QtCore.QRect(50, 170, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Email_Text.setFont(font)
        self.Email_Text.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(255,255,255,200);\n"
"padding-bottom:7px;\n"
"color:rgba(255,255,255,200);")
        self.Email_Text.setObjectName("Email_Text")
        self.Modify_Password_Button = QtWidgets.QPushButton(self.widget)
        self.Modify_Password_Button.setGeometry(QtCore.QRect(70, 340, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Modify_Password_Button.setFont(font)
        self.Modify_Password_Button.setStyleSheet("QPushButton#Modify_Password_Button{\n"
"background-color:rgba(16,30,41,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#Modify_Password_Button:hover{\n"
"background-color:rgba(5,50,118,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#Modify_Password_Button:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(10,65,118,100);\n"
"}")
        self.Modify_Password_Button.setObjectName("Modify_Password_Button")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 80, 80))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/png/images/登录.png"))
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(240, 0, 91, 55))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Exit_Button = QtWidgets.QPushButton(self.frame)
        self.Exit_Button.setGeometry(QtCore.QRect(65, 15, 30, 30))
        self.Exit_Button.setStyleSheet("QPushButton#Exit_Button{\n"
"background-color:rgba(30,30,40,240);\n"
"color:rgba(255,255,255,240);\n"
"border:none;\n"
"}\n"
"QPushButton#Exit_Button:hover{\n"
"background-color:rgba(140,40,58,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#Exit_Button:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(10,65,118,100);\n"
"}")
        self.Exit_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/images/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_Button.setIcon(icon)
        self.Exit_Button.setObjectName("Exit_Button")
        self.Min_Button = QtWidgets.QPushButton(self.frame)
        self.Min_Button.setGeometry(QtCore.QRect(30, 15, 30, 30))
        self.Min_Button.setStyleSheet("QPushButton#Min_Button{\n"
"background-color:rgba(30,30,40,240);\n"
"color:rgba(255,255,255,200);\n"
"border:none;\n"
"}\n"
"QPushButton#Min_Button:hover{\n"
"background-color:rgba(140,40,58,150);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#Min_Button:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(10,65,118,100);\n"
"}")
        self.Min_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/images/最小化3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Min_Button.setIcon(icon1)
        self.Min_Button.setObjectName("Min_Button")
        self.Password_New_Text = QtWidgets.QLineEdit(self.widget)
        self.Password_New_Text.setGeometry(QtCore.QRect(50, 250, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Password_New_Text.setFont(font)
        self.Password_New_Text.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(255,255,255,200);\n"
"padding-bottom:7px;\n"
"color:rgba(255,255,255,200);")
        self.Password_New_Text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_New_Text.setObjectName("Password_New_Text")

        self.retranslateUi(Form)
        self.Exit_Button.clicked.connect(Form.exit)
        self.Modify_Password_Button.clicked.connect(Form.modify_password)
        self.Min_Button.clicked.connect(Form.min)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Email_Text.setPlaceholderText(_translate("Form", "Email"))
        self.Modify_Password_Button.setText(_translate("Form", "Modify"))
        self.Password_New_Text.setPlaceholderText(_translate("Form", "New Password"))

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.m_flag = True
            self.m_Position = event.globalPos() - self.pos()  # 获取鼠标相对窗口的位置
            event.accept()
            self.setCursor(QCursor(Qt.OpenHandCursor))  # 更改鼠标图标

    def mouseMoveEvent(self, QMouseEvent):
        if Qt.LeftButton and self.m_flag:
            self.move(QMouseEvent.globalPos() - self.m_Position)  # 更改窗口位置
            QMouseEvent.accept()

    def mouseReleaseEvent(self, QMouseEvent):
        self.m_flag = False
        self.setCursor(QCursor(Qt.ArrowCursor))
