# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\大三上\计算机通信网络\大作业\新建文件夹\src\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 250, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 250, 50))
        self.label.setStyleSheet("background-color: rgba(30,30,40,240);\n"
"border-radius:10px;")
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(0, 50, 250, 550))
        self.listWidget.setStyleSheet("QListWidget\n"
"{\n"
"    color:rgb(200,200,200);\n"
"    border:3px solid gray;\n"
"    padding:20px 0px 0px 0px;\n"
"}\n"
"/**列表项*/\n"
"QListWidget::item\n"
"{\n"
"    color:rgb(200,200,200);\n"
"    height:40px;\n"
"    padding-left:20px;\n"
"    border:0px solid gray;\n"
"}\n"
"/**列表项扫过*/\n"
"QListWidget::item:hover\n"
"{\n"
"    color:rgb(255,255,255);\n"
"   \n"
"}\n"
"/**列表项选中*/\n"
"QListWidget::item::selected:active\n"
"{ \n"
"    color:white;\n"
"    border-width:0;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    color:white;\n"
"    border-width:0;\n"
"}\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(250, 0, 550, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 72, 15))
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(250, 50, 550, 550))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 531, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit.setGeometry(QtCore.QRect(10, 380, 531, 87))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 490, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(Form.send_action)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(Form.change)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.pushButton_2.setText(_translate("Form", "发送"))
